/**
 * Divine Rays — End-User UI polish v1
 * Spacing, buttons, cards, forms, tables, background.
 * Scoped to #portal-customer only — does not touch agent/admin.
 * Credit: Boyz at the Back LRK · All Rights Reserved
 */
(function () {
  'use strict';
  if (window.__DR_ENDUSER_UI_V1) return;
  window.__DR_ENDUSER_UI_V1 = 1;

  var STYLE_ID = 'dr-enduser-ui-css';

  var CSS = [
    '#portal-customer{',
    '  --eu-pad:1.25rem;',
    '  --eu-gap:1rem;',
    '  --eu-radius:14px;',
    '  --eu-radius-sm:10px;',
    '  --eu-border:rgba(139,124,247,0.22);',
    '  --eu-surface:rgba(22,20,36,0.82);',
    '  --eu-surface-2:rgba(32,28,52,0.9);',
    '  --eu-text:#eeeef6;',
    '  --eu-muted:#9494ae;',
    '  --eu-accent:#a78bfa;',
    '  --eu-primary:#7c6af0;',
    '  box-sizing:border-box;',
    '  padding:1.15rem 1.35rem 2rem;',
    '  max-width:960px;',
    '  margin:0 auto;',
    '  width:100%',
    '}',
    '#portal-customer *,#portal-customer *::before,#portal-customer *::after{box-sizing:border-box}',

    '#portal-customer .customer-tabs{',
    '  display:flex;flex-wrap:wrap;gap:0.4rem;',
    '  margin:0 0 1.35rem;padding:0.35rem;',
    '  background:rgba(0,0,0,0.28);',
    '  border:1px solid var(--eu-border);',
    '  border-radius:12px',
    '}',
    '#portal-customer .customer-tabs .ctab,',
    '#portal-customer .customer-tabs button{',
    '  flex:1;min-width:7rem;',
    '  border:none;cursor:pointer;font-family:inherit;',
    '  padding:0.6rem 0.9rem;border-radius:9px;',
    '  font-size:0.88rem;font-weight:600;',
    '  background:transparent;color:var(--eu-muted);',
    '  transition:background .15s,color .15s',
    '}',
    '#portal-customer .customer-tabs .ctab:hover,',
    '#portal-customer .customer-tabs button:hover{',
    '  color:var(--eu-text);background:rgba(139,124,247,0.12)',
    '}',
    '#portal-customer .customer-tabs .ctab.active,',
    '#portal-customer .customer-tabs button.active{',
    '  background:linear-gradient(135deg,#7c6af0,#9b8afb);',
    '  color:#fff;box-shadow:0 4px 14px rgba(124,106,240,0.35)',
    '}',

    '#portal-customer h2,#portal-customer h3{',
    '  margin:0 0 0.75rem;font-weight:700;letter-spacing:-0.01em;color:var(--eu-text)',
    '}',
    '#portal-customer h2{font-size:1.25rem}',
    '#portal-customer h3{font-size:1.05rem}',
    '#portal-customer p{margin:0 0 0.75rem;color:var(--eu-muted);line-height:1.5;font-size:0.9rem}',

    '#portal-customer .ticket-form,',
    '#portal-customer .comments-section,',
    '#portal-customer .ticket-detail,',
    '#portal-customer #cust-ticket-detail,',
    '#portal-customer .track-box,',
    '#portal-customer .success-box,',
    '#portal-customer .dr-eu-faq,',
    '#portal-customer .dr-eu-csat{',
    '  background:var(--eu-surface)!important;',
    '  border:1px solid var(--eu-border)!important;',
    '  border-radius:var(--eu-radius)!important;',
    '  padding:1.15rem 1.25rem!important;',
    '  margin-bottom:1rem!important;',
    '  box-shadow:0 8px 28px rgba(0,0,0,0.18)',
    '}',

    '#portal-customer #my-tickets-list{',
    '  display:flex;flex-direction:column;gap:0.7rem',
    '}',
    '#portal-customer .ticket-card{',
    '  background:var(--eu-surface)!important;',
    '  border:1px solid var(--eu-border)!important;',
    '  border-radius:var(--eu-radius)!important;',
    '  padding:1rem 1.15rem!important;',
    '  display:grid!important;',
    '  grid-template-columns:1fr auto!important;',
    '  gap:0.85rem!important;',
    '  align-items:center!important;',
    '  cursor:pointer;',
    '  transition:border-color .15s,box-shadow .15s,transform .12s',
    '}',
    '#portal-customer .ticket-card:hover{',
    '  border-color:rgba(167,139,250,0.5)!important;',
    '  box-shadow:0 6px 20px rgba(124,106,240,0.15);',
    '  transform:translateY(-1px)',
    '}',
    '#portal-customer .ticket-card h4{',
    '  margin:0 0 0.35rem!important;',
    '  font-size:0.98rem!important;',
    '  font-weight:650!important;',
    '  color:var(--eu-text)!important;',
    '  display:flex;align-items:center;flex-wrap:wrap;gap:0.25rem',
    '}',
    '#portal-customer .ticket-meta{',
    '  display:flex;flex-wrap:wrap;gap:0.45rem 0.75rem;',
    '  font-size:0.78rem;color:var(--eu-muted)',
    '}',
    '#portal-customer .ticket-meta .ticket-id{',
    '  color:var(--eu-accent);font-weight:600;font-variant-numeric:tabular-nums',
    '}',
    '#portal-customer .badges{',
    '  display:flex;flex-direction:column;align-items:flex-end;gap:0.35rem',
    '}',
    '#portal-customer .badge{',
    '  display:inline-flex;align-items:center;',
    '  padding:0.22rem 0.55rem;border-radius:999px;',
    '  font-size:0.7rem;font-weight:700;letter-spacing:0.02em;',
    '  text-transform:capitalize',
    '}',

    '#portal-customer .btn,',
    '#portal-customer button.btn,',
    '#portal-customer button[type="submit"],',
    '#portal-customer #cust-reply-form button,',
    '#portal-customer #customer-form button[type="submit"]{',
    '  appearance:none;border:none;cursor:pointer;font-family:inherit;',
    '  display:inline-flex;align-items:center;justify-content:center;gap:0.4rem;',
    '  padding:0.62rem 1.15rem;border-radius:10px;',
    '  font-size:0.88rem;font-weight:650;line-height:1.2;',
    '  transition:background .15s,box-shadow .15s,transform .1s,opacity .15s',
    '}',
    '#portal-customer .btn:active{transform:scale(0.98)}',
    '#portal-customer .btn-primary,',
    '#portal-customer button.btn-primary,',
    '#portal-customer #cust-reply-form button[type="submit"],',
    '#portal-customer #customer-form button[type="submit"]{',
    '  background:linear-gradient(135deg,#7c6af0 0%,#9b8afb 100%)!important;',
    '  color:#fff!important;',
    '  box-shadow:0 4px 16px rgba(124,106,240,0.35)',
    '}',
    '#portal-customer .btn-primary:hover,',
    '#portal-customer #cust-reply-form button[type="submit"]:hover{',
    '  background:linear-gradient(135deg,#8b7af5 0%,#a99aff 100%)!important;',
    '  box-shadow:0 6px 20px rgba(124,106,240,0.45)',
    '}',
    '#portal-customer .btn-secondary,',
    '#portal-customer button.btn-secondary{',
    '  background:var(--eu-surface-2)!important;',
    '  color:var(--eu-text)!important;',
    '  border:1px solid var(--eu-border)!important',
    '}',
    '#portal-customer .btn-secondary:hover{',
    '  border-color:rgba(167,139,250,0.45)!important;',
    '  background:rgba(139,124,247,0.12)!important',
    '}',
    '#portal-customer .btn:disabled,',
    '#portal-customer button:disabled{opacity:0.55;cursor:not-allowed;transform:none}',

    '#portal-customer .form-group{margin-bottom:0.95rem}',
    '#portal-customer label,#portal-customer .form-group label{',
    '  display:block;margin-bottom:0.35rem;',
    '  font-size:0.8rem;font-weight:600;color:var(--eu-muted)',
    '}',
    '#portal-customer input[type="text"],',
    '#portal-customer input[type="email"],',
    '#portal-customer input[type="password"],',
    '#portal-customer input[type="search"],',
    '#portal-customer input[type="number"],',
    '#portal-customer input:not([type="checkbox"]):not([type="radio"]):not([type="file"]),',
    '#portal-customer select,',
    '#portal-customer textarea{',
    '  width:100%;',
    '  padding:0.65rem 0.85rem;',
    '  border-radius:var(--eu-radius-sm);',
    '  border:1px solid var(--eu-border);',
    '  background:rgba(0,0,0,0.28);',
    '  color:var(--eu-text);',
    '  font:inherit;font-size:0.9rem;',
    '  outline:none;',
    '  transition:border-color .15s,box-shadow .15s',
    '}',
    '#portal-customer input:focus,',
    '#portal-customer select:focus,',
    '#portal-customer textarea:focus{',
    '  border-color:rgba(167,139,250,0.65);',
    '  box-shadow:0 0 0 3px rgba(124,106,240,0.22)',
    '}',
    '#portal-customer textarea{min-height:5.5rem;resize:vertical;line-height:1.45}',
    '#portal-customer select{',
    '  appearance:none;',
    '  background-image:url("data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'12\' height=\'8\' viewBox=\'0 0 12 8\'%3E%3Cpath fill=\'%23a78bfa\' d=\'M1 1l5 5 5-5\'/%3E%3C/svg%3E");',
    '  background-repeat:no-repeat;',
    '  background-position:right 0.75rem center;',
    '  background-size:11px 7px;',
    '  padding-right:2rem',
    '}',
    '#portal-customer .form-actions,',
    '#portal-customer #cust-reply-form .form-actions{',
    '  display:flex;flex-wrap:wrap;gap:0.55rem;',
    '  align-items:center;margin-top:0.75rem',
    '}',
    '#portal-customer #cust-reply-form{',
    '  margin-top:0.5rem;padding-top:0.85rem;',
    '  border-top:1px solid rgba(139,124,247,0.15)',
    '}',

    '#portal-customer #cust-comments-list{',
    '  margin-bottom:0.85rem;max-height:min(52vh,480px);overflow-y:auto;',
    '  padding-right:0.25rem',
    '}',
    '#portal-customer #cust-comments-list::-webkit-scrollbar{width:6px}',
    '#portal-customer #cust-comments-list::-webkit-scrollbar-thumb{',
    '  background:rgba(167,139,250,0.35);border-radius:99px',
    '}',

    '#portal-customer .meta-chip{',
    '  display:inline-flex;align-items:center;gap:0.35rem;',
    '  padding:0.3rem 0.65rem;margin:0.2rem 0.35rem 0.2rem 0;',
    '  border-radius:8px;font-size:0.75rem;',
    '  background:rgba(0,0,0,0.25);border:1px solid var(--eu-border);',
    '  color:var(--eu-muted)',
    '}',
    '#portal-customer .meta-chip .meta-k{font-weight:600;color:var(--eu-accent)}',
    '#portal-customer .detail-description{',
    '  margin:0.85rem 0;padding:0.85rem 1rem;',
    '  border-radius:var(--eu-radius-sm);',
    '  background:rgba(0,0,0,0.22);',
    '  border:1px solid rgba(139,124,247,0.12);',
    '  color:var(--eu-text);line-height:1.5;font-size:0.92rem',
    '}',

    '#portal-customer table{',
    '  width:100%;border-collapse:separate;border-spacing:0;',
    '  font-size:0.88rem;margin:0.5rem 0 1rem;',
    '  border:1px solid var(--eu-border);border-radius:var(--eu-radius);overflow:hidden',
    '}',
    '#portal-customer th,#portal-customer td{',
    '  padding:0.65rem 0.85rem;text-align:left;',
    '  border-bottom:1px solid var(--eu-border)',
    '}',
    '#portal-customer th{',
    '  font-size:0.75rem;font-weight:700;text-transform:uppercase;',
    '  letter-spacing:0.04em;color:var(--eu-muted);',
    '  background:rgba(0,0,0,0.2)',
    '}',
    '#portal-customer tr:hover td{background:rgba(139,124,247,0.06)}',

    '#portal-customer #dr-cust-ticket-toolbar{margin-bottom:1rem!important;border-radius:12px!important}',
    '#portal-customer .empty-state,#portal-customer .dr-eu-empty{',
    '  text-align:center;padding:2.25rem 1.5rem!important;',
    '  border-radius:var(--eu-radius)!important;',
    '  border:1px dashed rgba(139,124,247,0.35)!important;',
    '  background:rgba(22,20,36,0.55)!important',
    '}',
    '#portal-customer #btn-cust-back{margin-bottom:0.85rem}',

    'html[data-theme="light"] #portal-customer{',
    '  --eu-border:rgba(109,94,245,0.2);',
    '  --eu-surface:#ffffff;',
    '  --eu-surface-2:#f5f3ff;',
    '  --eu-text:#1e1b4b;',
    '  --eu-muted:#5b5675;',
    '  --eu-accent:#6d5ef5',
    '}',
    'html[data-theme="light"] #portal-customer .customer-tabs{background:rgba(109,94,245,0.08)}',
    'html[data-theme="light"] #portal-customer input,',
    'html[data-theme="light"] #portal-customer select,',
    'html[data-theme="light"] #portal-customer textarea{',
    '  background:#fff;color:#1e1b4b;border-color:rgba(109,94,245,0.25)',
    '}',
    'html[data-theme="light"] #portal-customer .detail-description{background:#f8f7ff;color:#1e1b4b}',
    'html[data-theme="light"] #portal-customer .meta-chip{background:#f5f3ff;color:#5b5675}',

    '@media (max-width:640px){',
    '  #portal-customer{padding:0.85rem 0.9rem 1.75rem}',
    '  #portal-customer .ticket-card{grid-template-columns:1fr!important}',
    '  #portal-customer .badges{flex-direction:row;justify-content:flex-start}',
    '  #portal-customer .customer-tabs .ctab{min-width:0;flex:1;padding:0.55rem 0.4rem;font-size:0.8rem}',
    '}',
  ].join('');

  function inject() {
    var el = document.getElementById(STYLE_ID);
    if (!el) {
      el = document.createElement('style');
      el.id = STYLE_ID;
      document.head.appendChild(el);
    }
    el.textContent = CSS;
  }

  inject();
  setTimeout(inject, 500);
  setTimeout(inject, 2000);

  setInterval(function () {
    var el = document.getElementById(STYLE_ID);
    if (el && el.parentNode) el.parentNode.appendChild(el);
  }, 8000);

  window.DREndUserUI = { refresh: inject };
})();
